apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: kong-declaratives
 namespace: kong
spec: 
 storageClassName: standard
 accessModes:
  - ReadWriteMany
 resources:
  requests:
   storage: 1Gi