apiVersion: v1
kind: PersistentVolume
metadata:
  name: kong-declaratives
  #namespace: kong-namespace
  labels:
   type: local
spec: 
  capacity: 
    storage: 2Gi 
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/kongdeclarative/
    type: Directory