apiVersion: v1
kind: Service
metadata:
 name: kong-service
spec:
 selector:
  app: kong
 type: LoadBalancer 
 ports:
  - protocol: TCP
    name: tcp-8000
    port: 8000
    targetPort: 8000
    nodePort: 30000
  - protocol: TCP
    name: tcp-8443
    port: 8443
    targetPort: 8443
    nodePort: 30443
  - protocol: TCP
    name: tcp-8001
    port: 8001
    targetPort: 8001
    nodePort: 30001
  - protocol: TCP
    name: tcp-8444
    port: 8444
    targetPort: 8444
    nodePort: 30444
  - protocol: TCP
    name: tcp-8002
    port: 8002
    targetPort: 8002
    nodePort: 30002
  - protocol: TCP
    name: tcp-8445
    port: 8445
    targetPort: 8445
    nodePort: 30445
  - protocol: TCP
    name: tcp-8003
    port: 8003
    targetPort: 8003
    nodePort: 30003
  - protocol: TCP
    name: tcp-8004
    port: 8004
    targetPort: 8004
    nodePort: 30004