apiVersion: v1
kind: Namespace
metadata:
  name: database
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kong-database
  #namespace: kong-namespace
  labels:
   type: local
spec: 
  capacity: 
    storage: 100M
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /kongdatabase/
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: kong-database
 namespace: database
 labels:
  app: postgres
spec: 
 storageClassName: manual
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 100M
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: kong-database-deployment
 namespace: database
 labels:
  app: postgres
spec:
 replicas: 1
 selector:
  matchLabels:
   app: postgres
 template:
  metadata:
   labels:
    app: postgres
  spec:
   securityContext:
    runAsUser: 1000
    fsGroup: 1000
   containers:
    - name: postgres
      image: postgres:latest
      #command: -c chmod -R 777 /var/lib/postgresql/data/pgdata
      env:
       - name: POSTGRES_DB
         value: kong
       - name: POSTGRES_USER
         value: kong
       - name: POSTGRES_PASSWORD
         value: password
       - name: PGDATA
         value: /var/lib/postgresql/data/pgdata
       - name: POSTGRES_INITDB_ARGS
         value: "-D /var/lib/postgresql/data/pgdata"
      ports:
       - containerPort: 5432
      volumeMounts:
       - name: kong-database
         mountPath: /var/lib/postgresql/data
         subPath: pgdata
      #securityContext:
       #privileged: true # Processes in privileged containers are essentially equivalent to root on the host.
   #initContainers:
    #- name: change-ownership-container
     # image: postgres:latest
     # command: ["/bin/chmod","-R","777", "/var/lib/postgresql/data/pgdata"] #["/bin/chown","-R","999:999", "/var/lib/postgresql/data/pgdata"]
     # securityContext:
      #  runAsUser: 0
       # privileged: true
      #volumeMounts:
      #- name: kong-database
       # mountPath: /var/lib/postgresql/data/
        #subPath: pgdata
   volumes:
     - name: kong-database
       #hostPath:
       # directory location on host
       #path: /data/kongdeclerative
       # this field is optional
       #type: Directory
       persistentVolumeClaim:
        claimName: kong-database
---
apiVersion: v1
kind: Service
metadata:
 name: kong-database-service
 namespace: database
spec:
 selector:
  app: postgres
 ports:
  - protocol: TCP
    name: tcp-5432
    port: 5432
    targetPort: 5432
