 _format_version: "1.1"
 _transform: true

 services:
 - host: httpbin # 172.19.0.2 of
   name: example_service
   port: 80
   protocol: http
   routes:
    - name: example_route
      paths:
       - /get
      strip_path: false
    - name: example_route2
      paths:
       - /post
      strip_path: false
# plugins:
#  - name: basic-auth
#    service: example_service
#    config: 
#      hide_credentials: true
# consumers:
#  - username: admin
#    custom_id: "1234"
# basicauth_credentials:
#  - consumer: admin
#    username: Martijn
#    password: test1234